E-Commerce/Controllers/CartController.cs
using E_Commerce.DataAccessDataAccess.Repository.IRepository;
using E_Commerce.Models.OrderFile;
using E_Commerce.Models.ShoppingCartFile;
using E_Commerce.Models.UserFile;
using E_Commerce.Models.ViewModels;
using E_Commerce.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using Stripe.Checkout;
using System.Security.Claims;

namespace E_Commerce.Controllers
{
    // i didn't put this in the area of customer so when you copy paste that to the customer area uncomment this
    //[Area("customer")]

    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public ShoppingCartVM ShoppingCartVM { get; set; }
        public CartController(IUnitOfWork _unitOfWork)
        {
            this._unitOfWork = _unitOfWork;
        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var UserId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM = new()
            {
                ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicaitonUserId == UserId, includeProperties:"ProductItem"),
                Order=new()
               
                
            };
            
            /// Calculating the total price
            foreach (var cart in ShoppingCartVM.ShoppingCartList)
            {
                
                cart.Price = cart.ProductItem.Price * cart.Quantity; // if you want to view every shopping cart item specific price
                ShoppingCartVM.Order.TotalPrice += (cart.ProductItem.Price * cart.Quantity);
            }

            return View(ShoppingCartVM);
        }

        public IActionResult Summary()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var UserId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM = new()
            {
                ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicaitonUserId == UserId, includeProperties: "ProductItem"),
                Order = new Order()
            };

            ShoppingCartVM.Order.User = _unitOfWork.User.Get(u => u.Id == UserId);
            ShoppingCartVM.Order.Name = ShoppingCartVM.Order.User.FirstName + " " + ShoppingCartVM.Order.User.LastName;
            ShoppingCartVM.Order.PhoneNumber = ShoppingCartVM.Order.User.PhoneNumber;
            ShoppingCartVM.Order.StreetAddress = ShoppingCartVM.Order.User.StreetAddress;
            ShoppingCartVM.Order.City = ShoppingCartVM.Order.User.City;
            ShoppingCartVM.Order.State = ShoppingCartVM.Order.User.State;
            ShoppingCartVM.Order.PostalCode = ShoppingCartVM.Order.User.PostalCode;

            foreach (var cart in ShoppingCartVM.ShoppingCartList)
            {

                cart.Price = cart.ProductItem.Price * cart.Quantity; // if you want to view every shopping cart item specific price
                ShoppingCartVM.Order.TotalPrice += cart.Price;
            }
           
            return View(ShoppingCartVM);
        }
        [HttpPost]
        [ActionName("Summary")]
        public IActionResult SummaryPost()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var UserId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM.ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicaitonUserId == UserId, includeProperties: "ProductItem");
            ShoppingCartVM.Order.OrderDate = System.DateTime.Now;
            ShoppingCartVM.Order.UserId = UserId;

            User Applicationuser = _unitOfWork.User.Get(u => u.Id == UserId);

            foreach (var cart in ShoppingCartVM.ShoppingCartList)
            {

                cart.Price = cart.ProductItem.Price * cart.Quantity; // if you want to view every shopping cart item specific price
                ShoppingCartVM.Order.TotalPrice += (cart.ProductItem.Price * cart.Quantity);
            }
            ShoppingCartVM.Order.PaymentStatus = SD.PaymentStatusPending;
            ShoppingCartVM.Order.OrderStatuss = SD.StatusPending;
            ShoppingCartVM.Order.AddressId = null;
            ShoppingCartVM.Order.ImportancyId = null;
            ShoppingCartVM.Order.OrderStatusId = null;
            ShoppingCartVM.Order.TaxId = null;
            ShoppingCartVM.Order.PaymentMethodId = null;

            if (ModelState.IsValid)
            {
                _unitOfWork.Order.Add(ShoppingCartVM.Order);
                _unitOfWork.Save();
            }
            else
            {
                return View(ShoppingCartVM);
            }
            foreach (var cart in ShoppingCartVM.ShoppingCartList)
            {
                OrderLine orderDetail = new()
                {
                    ProductItemId = cart.ProductItemId,
                    OrderId = ShoppingCartVM.Order.Id,
                    Price = cart.Price,
                    Quantity = cart.Quantity
                };
                if (ModelState.IsValid)
                {
                    _unitOfWork.OrderLine.Add(orderDetail);
                    _unitOfWork.Save();
                }
            }
            //it is a regular customer account and we need to capture payment
            //stripe logic
            //var domain = "https://localhost:44355/";
            var domain = Request.Scheme + "://" + Request.Host.Value + "/";
            var options = new SessionCreateOptions
            {
                SuccessUrl = domain + $"Cart/OrderConfirmation?id={ShoppingCartVM.Order.Id}",
                CancelUrl = domain + "Cart/index",
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
            };
            foreach (var item in ShoppingCartVM.ShoppingCartList)
            {
                var sessionLineItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.ProductItem.Price * 100), // $20.50 => 2050
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.ProductItem.SKU
                        }
                    },
                    Quantity = item.Quantity
                };
                options.LineItems.Add(sessionLineItem);

            }
            var service = new SessionService();
            Session session = service.Create(options);
            _unitOfWork.Order.UpdateStripePaymentID(ShoppingCartVM.Order.Id, session.Id, session.PaymentIntentId);
            _unitOfWork.Save();
            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303); 

            //return RedirectToAction(nameof(OrderConfirmation), new {id=ShoppingCartVM.Order.Id});
        }

        public IActionResult OrderConfirmation(int id)
        {
            Order orderHeader = _unitOfWork.Order.Get(u => u.Id == id, includeProperties: "User");
            if (orderHeader.PaymentStatus != SD.PaymentStatusDelayedPayment)
            {
                //this is an order by customer

                var service = new SessionService();
                Session session = service.Get(orderHeader.SessionId);

                if (session.PaymentStatus.ToLower() == "paid")
                {
                    _unitOfWork.Order.UpdateStripePaymentID(id, session.Id, session.PaymentIntentId);
                    _unitOfWork.Order.UpdateStatus(id, SD.StatusApproved, SD.PaymentStatusApproved);
                    _unitOfWork.Save();
                }

                HttpContext.Session.Clear(); // To Clear the view of shopping cart to 0
            }

            List<ShoppingCart> shoppingCarts = _unitOfWork.ShoppingCart
                .GetAll(u => u.ApplicaitonUserId == orderHeader.UserId).ToList();

            _unitOfWork.ShoppingCart.RemoveRange(shoppingCarts);
            _unitOfWork.Save();

            return View(id);
        }

        public IActionResult Plus(int CartId) 
        {
            ShoppingCart cartFromDb = _unitOfWork.ShoppingCart.Get(u => u.Id == CartId);
            cartFromDb.Quantity += 1;
            _unitOfWork.ShoppingCart.Update(cartFromDb);
           _unitOfWork.Save();
            TempData["Success"] = "Product Incremented Successfully";
            return RedirectToAction("Index");
        }

        public IActionResult Minus(int CartId)
        {
            ShoppingCart cartFromDb = _unitOfWork.ShoppingCart.Get(u => u.Id == CartId, tracked:true);
            if(cartFromDb.Quantity <= 1)
            {
                HttpContext.Session.SetInt32(SD.SessionCart, _unitOfWork.ShoppingCart.GetAll(u => u.ApplicaitonUserId == cartFromDb.ApplicaitonUserId).Count() - 1);
                _unitOfWork.ShoppingCart.Remove(cartFromDb);

            }
            else
            {
                cartFromDb.Quantity -= 1;
                _unitOfWork.ShoppingCart.Update(cartFromDb);
                TempData["Success"] = "Product Decremented Successfully";
            }

            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Remove(int CartId)
        {
            ShoppingCart cartFromDb = _unitOfWork.ShoppingCart.Get(u => u.Id == CartId, tracked:true);
            HttpContext.Session.SetInt32(SD.SessionCart, _unitOfWork.ShoppingCart.GetAll(u => u.ApplicaitonUserId == cartFromDb.ApplicaitonUserId).Count()-1);
            _unitOfWork.ShoppingCart.Remove(cartFromDb);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

    }
}

E-Commerce/Controllers/OrderController.cs
using E_Commerce.DataAccessDataAccess.Repository.IRepository;
using E_Commerce.Models.OrderFile;
using E_Commerce.Models.ViewModels;
using E_Commerce.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using System.Security.Claims;

namespace E_Commerce.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public OrderVM OrderVM { get; set; }
        public OrderController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }
        [Authorize]
        public IActionResult Index()
        {
            IEnumerable<Order> objOrderHeaders;


            if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
            {
                objOrderHeaders = _unitOfWork.Order.GetAll(includeProperties: "User").ToList();
            }
            else
            {

                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

                objOrderHeaders = _unitOfWork.Order
                    .GetAll(u => u.UserId == userId, includeProperties: "User");
            }
            return View(objOrderHeaders);
        }
        public IActionResult Details(int? OrderId)
        {
            OrderVM = new()
            {
                OrderHeader = _unitOfWork.Order.Get(u => u.Id == OrderId, includeProperties: "User"),
                OrderDetail = _unitOfWork.OrderLine.GetAll(u => u.OrderId == OrderId, includeProperties: "Product")
            };
            return View(OrderVM);
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult UpdateOrderDetail()
        {
            var orderHeaderFromDb = _unitOfWork.Order.Get(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeaderFromDb.Name = OrderVM.OrderHeader.Name;
            orderHeaderFromDb.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
            orderHeaderFromDb.StreetAddress = OrderVM.OrderHeader.StreetAddress;
            orderHeaderFromDb.City = OrderVM.OrderHeader.City;
            orderHeaderFromDb.State = OrderVM.OrderHeader.State;
            orderHeaderFromDb.PostalCode = OrderVM.OrderHeader.PostalCode;

            if (!string.IsNullOrEmpty(OrderVM.OrderHeader.Carrier))
            {
                orderHeaderFromDb.Carrier = OrderVM.OrderHeader.Carrier;
            }
            if (!string.IsNullOrEmpty(OrderVM.OrderHeader.TrackingNumber))
            {
                orderHeaderFromDb.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
            }
            _unitOfWork.Order.Update(orderHeaderFromDb);
            _unitOfWork.Save();

            return RedirectToAction(nameof(Details), new { orderId = orderHeaderFromDb.Id });

        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult StartProcessing()
        {
            _unitOfWork.Order.UpdateStatus(OrderVM.OrderHeader.Id, SD.StatusInProcess);
            _unitOfWork.Save();
            TempData["Success"] = "Order Details Updated Successfully.";
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult ShipOrder()
        {

            var orderHeader = _unitOfWork.Order.Get(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeader.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
            orderHeader.Carrier = OrderVM.OrderHeader.Carrier;
            orderHeader.OrderStatuss = SD.StatusShipped;
            orderHeader.ShippingDate = DateTime.Now;
            if (orderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                orderHeader.PaymentDueDate = DateOnly.FromDateTime(DateTime.Now.AddDays(30));
            }

            _unitOfWork.Order.Update(orderHeader);
            _unitOfWork.Save();
            TempData["Success"] = "Order Shipped Successfully.";
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult CancelOrder()
        {

            var orderHeader = _unitOfWork.Order.Get(u => u.Id == OrderVM.OrderHeader.Id);

            if (orderHeader.PaymentStatus == SD.PaymentStatusApproved)
            {
                var options = new RefundCreateOptions
                {
                    Reason = RefundReasons.RequestedByCustomer,
                    PaymentIntent = orderHeader.PaymentIntentId
                };

                var service = new RefundService();
                Refund refund = service.Create(options);

                _unitOfWork.Order.UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusRefunded);
            }
            else
            {
                _unitOfWork.Order.UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusCancelled);
            }
            _unitOfWork.Save();
            TempData["Success"] = "Order Cancelled Successfully.";
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });

        }
    }
}

E-Commerce/ViewComponents/ShoppingCartViewComponent.cs
using E_Commerce.DataAccessDataAccess.Repository.IRepository;
using E_Commerce.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace E_Commerce.ViewComponents
{
    public class ShoppingCartViewComponent:ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {
                if(HttpContext.Session.GetInt32(SD.SessionCart) == null)
                {
                    HttpContext.Session.SetInt32(SD.SessionCart, _unitOfWork.ShoppingCart.GetAll(s => s.ApplicaitonUserId == claim.Value).Count());
                }

                return View(HttpContext.Session.GetInt32(SD.SessionCart));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }

        }
    }
}

E-Commerce/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Nilura - Your Online Clothing Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
    <link href="~/css/home.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/toastr.js/toastr.min.css" />
</head>

<body class="bg-light">
    <header class="fixed-top">
        <nav class="navbar navbar-expand-lg navbar-dark custom-gradient shadow-lg">
            <div class="container-fluid px-4">
                <a class="navbar-brand d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/images/logo.png" alt="Nilura Logo" class="img-fluid logo-transform" style="max-width: 140px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto align-items-center">
                        <li class="nav-item me-3">
                            <a class="nav-link" asp-controller="Order" asp-action="Index">
                                <i class="bi bi-list-check me-2"></i>Manage Orders
                            </a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown me-3">
                                <a class="nav-link dropdown-toggle" href="#" id="adminDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-shield-lock me-2"></i>Admin Panel
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="adminDropdown">
                                    <li><a asp-area="" asp-controller="Product" asp-action="Index" class="dropdown-item">
                                        <i class="bi bi-box-seam me-2"></i>Manage Products</a></li>
                                    <li><a asp-area="" asp-controller="Category" asp-action="Index" class="dropdown-item">
                                        <i class="bi bi-tag me-2"></i>Manage Categories</a></li>
                                    <li><a asp-area="" asp-controller="ProductItem" asp-action="Index" class="dropdown-item">
                                        <i class="bi bi-collection me-2"></i>Manage Items</a></li>
                                    <li><a asp-area="Identity" asp-page="/Account/Register" class="dropdown-item">
                                        <i class="bi bi-person-plus me-2"></i>Create User</a></li>
                                    <li><a asp-area="" asp-controller="User" asp-action="Index" class="dropdown-item">
                                        <i class="bi bi-people me-2"></i>Manage Users</a></li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item me-3">
                            <a asp-area="" asp-controller="Cart" asp-action="Index" class="nav-link position-relative">
                                <i class="bi bi-cart3 me-2"></i>
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>
                        <li class="nav-item">
                            <partial name="_LoginPartial" />
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container mt-5 pt-4">
        <main role="main" class="pb-5 page-content">
            @RenderBody()
        </main>
    </div>

    <footer class="footer custom-gradient-inverse text-white py-4 mt-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-4 text-center text-md-start">
                    <img src="/images/logo.png" alt="Nilura Logo" class="img-fluid mb-3" style="max-width: 100px;" />
                </div>
                <div class="col-md-4 text-center">
                    <p style="color:darkblue;" class="mb-0">&copy; 2024 Nilura | All Rights Reserved</p>
                    <p>
                        <a href="@Url.Action("Privacy", "Home")">Privacy Policy</a> |
                        <a href="@Url.Action("Privacy", "Home")">Terms of Service</a>
                    </p>

                </div>
                <div class="col-md-4 text-center text-md-end">
                    <div class="social-links">
                        <a href="#" class="text-white me-3 social-icon text-primary"><i class="fab fa-facebook-f"></i></a>
                        <a href="#" class="text-white me-3 social-icon text-info"><i class="fab fa-twitter"></i></a>
                        <a href="#" class="text-white me-3 social-icon text-danger"><i class="fab fa-instagram"></i></a>
                        <a href="#" class="text-white social-icon text-dark"><i class="fab fa-linkedin-in"></i></a>
                    </div>

                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="~/toastr.js/toastr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<style>
    :root {
        --primary-color: #0056b3;
        --secondary-color: #ffd700;
        --dark-background: #1a1a2e;
        --light-background: #f4f4f4;
    }

    body {
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        background-color: var(--light-background);
        color: var(--dark-background);
    }

    /* Gradient Backgrounds */
    .custom-gradient {
        background: linear-gradient(135deg, var(--primary-color), #2c3e50);
        transition: background 0.3s ease;
    }

    .custom-gradient-inverse {
        background: linear-gradient(315deg, var(--dark-background), #2c3e50);
    }

    
    .navbar-brand img {
        max-height: 50px;
        object-fit: contain;
    }
    /* Navigation Styling */
    .navbar {
        backdrop-filter: blur(10px);
        background-color: rgba(0, 86, 179, 0.9);
        padding: 0.75rem 0;
        padding-top: 0.25rem !important;
        padding-bottom: 0.25rem !important;
    }

    .navbar-nav .nav-link {
        color: white;
        font-weight: 500;
        transition: all 0.3s ease;
        position: relative;
    }

    .navbar-nav .nav-link::after {
        content: '';
        position: absolute;
        width: 0;
        height: 2px;
        bottom: -5px;
        left: 50%;
        background-color: var(--secondary-color);
        transition: all 0.3s ease;
    }

    .navbar-nav .nav-link:hover::after {
        width: 100%;
        left: 0;
    }

    .navbar-nav .nav-link:hover {
        color: var(--secondary-color);
        transform: translateY(-3px);
    }

    /* Logo and Branding */
    .logo-transform {
        transition: transform 0.3s ease;
    }

    .logo-transform:hover {
        transform: scale(1.05);
    }

    .navbar-nav .nav-link i {
        margin-right: 0.25rem;
        font-size: 1rem;
    }

    /* Adjust container top padding to match smaller navbar */
    .container.mt-5 {
        padding-top: calc(1rem + 55px) !important;
    }

    /* Dropdown Styling */
    .dropdown-menu-dark {
        background-color: var(--dark-background);
        border: none;
    }

    .dropdown-item {
        color: white !important;
        transition: background-color 0.3s ease;
    }

    .dropdown-item:hover {
        background-color: rgba(255,255,255,0.1) !important;
        color: var(--secondary-color) !important;
    }

    /* Footer Styling */
    .footer {
        border-top: 4px solid var(--secondary-color);
        content: '';
        position: absolute;
        height: 6px;
        bottom: -5px;
       
    }

    .social-icon {
        font-size: 1.5rem;
        transition: color 0.3s ease, transform 0.3s ease;
    }

    .social-icon:hover {
        color: var(--secondary-color) !important;
        transform: scale(1.2) rotate(360deg);
    }

    .social-links .facebook {
        color: darkblue;
    }

    .social-links .twitter {
        color: skyblue;
    }

    .social-links .instagram {
        color: purple;
    }

    .social-links .linkedin {
        color: #0077b5;
    }


    /* Page Content Padding */
    .page-content {
        background-color: white;
        border-radius: 12px;
        padding: 2rem;
        box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);
    }
</style>

E-Commerce/Views/Shared/_NotificationPartial.cshtml
@if (TempData["Success"] is not null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/toastr.js/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["Success"]');
	</script>
}
@if (TempData["Error"] is not null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/toastr.js/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.error('@TempData["Error"]');
	</script>
}